blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/9gkc/AuthZGuard/security/advisories/new
    about: Please use private reporting for a vulnerability in AuthZGuard.

